<?php
	if ( ! defined( 'ABSPATH' ) ) exit;
	global $wpdb;
	$table_name   = $wpdb->prefix . "rich_web_video_slider_font_family";
	$table_name1  = $wpdb->prefix . "rich_web_video_slider_id";
	$table_name2  = $wpdb->prefix . "rich_web_video_slider_manager";
	$table_name3  = $wpdb->prefix . "rich_web_video_slider_videos";
	$table_name4  = $wpdb->prefix . "rich_web_video_slider_effects_data";
	$table_name5  = $wpdb->prefix . "rich_web_vs_effect_1";
	$table_name6  = $wpdb->prefix . "rich_web_vs_effect_2";
	$table_name7  = $wpdb->prefix . "rich_web_vs_effect_3";
	$table_name8  = $wpdb->prefix . "rich_web_vs_effect_4";
	$table_name9  = $wpdb->prefix . "rich_web_vs_effect_5";
	$table_name10 = $wpdb->prefix . "rich_web_vs_effect_6";
	$table_name11 = $wpdb->prefix . "rich_web_vs_effect_7";

	$sql  = 'CREATE TABLE IF NOT EXISTS ' .$table_name .' ( id INTEGER(10) UNSIGNED AUTO_INCREMENT, Font_family VARCHAR(255) NOT NULL, PRIMARY KEY (id))';
	$sql1 = 'CREATE TABLE IF NOT EXISTS ' .$table_name1 . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, Slider_ID INTEGER(10) NOT NULL, PRIMARY KEY (id))';
	$sql2 = 'CREATE TABLE IF NOT EXISTS ' .$table_name2 . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, Slider_Title VARCHAR(255) NOT NULL, Slider_Type VARCHAR(255) NOT NULL, Slider_Video_Quantity INTEGER(10) NOT NULL, PRIMARY KEY (id))';		
	$sql3 = 'CREATE TABLE IF NOT EXISTS ' .$table_name3 . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, Rich_Web_VSlider_Vid_Title VARCHAR(255) NOT NULL, Rich_Web_VSlider_Add_Desc LONGTEXT NOT NULL, Rich_Web_VSldier_Add_Img VARCHAR(255) NOT NULL, Rich_Web_VSldier_Add_Vid VARCHAR(255) NOT NULL, Rich_Web_VSldier_Add_Src VARCHAR(255) NOT NULL, Rich_Web_VSldier_Add_Link VARCHAR(255) NOT NULL, Rich_Web_VSldier_Add_ONT VARCHAR(255) NOT NULL, Slider_ID INTEGER(10) NOT NULL, PRIMARY KEY (id))';
	$sql4 = 'CREATE TABLE IF NOT EXISTS ' .$table_name4 . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, slider_vid_name VARCHAR(255) NOT NULL, slider_Vid_type VARCHAR(255) NOT NULL, PRIMARY KEY (id))';		
	$sql5 = 'CREATE TABLE IF NOT EXISTS ' .$table_name5 . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, RW_VS_ID VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Name VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Type VARCHAR(255) NOT NULL, Rich_Web_VS_CP_CE VARCHAR(255) NOT NULL, Rich_Web_VS_CP_EE VARCHAR(255) NOT NULL, Rich_Web_VS_CP_S VARCHAR(255) NOT NULL, Rich_Web_VS_CP_BlC VARCHAR(255) NOT NULL, Rich_Web_VS_CP_BlR VARCHAR(255) NOT NULL, Rich_Web_VS_CP_AS VARCHAR(255) NOT NULL, Rich_Web_VS_CP_PT VARCHAR(255) NOT NULL, Rich_Web_VS_CP_SS VARCHAR(255) NOT NULL, Rich_Web_VS_CS_AP VARCHAR(255) NOT NULL, Rich_Web_VS_CS_HP VARCHAR(255) NOT NULL, Rich_Web_VS_CS_RS VARCHAR(255) NOT NULL, Rich_Web_VS_CS_BSC VARCHAR(255) NOT NULL, Rich_Web_VS_CP_BW VARCHAR(255) NOT NULL, Rich_Web_VS_CP_BS VARCHAR(255) NOT NULL, Rich_Web_VS_CS_BC VARCHAR(255) NOT NULL, Rich_Web_VS_CP_BR VARCHAR(255) NOT NULL, Rich_Web_VS_CS_CN VARCHAR(255) NOT NULL, Rich_Web_VS_CS_NPB VARCHAR(255) NOT NULL, Rich_Web_VS_CP_NO VARCHAR(255) NOT NULL, Rich_Web_VS_CS_NT VARCHAR(255) NOT NULL, Rich_Web_VS_CP_NT VARCHAR(255) NOT NULL, Rich_Web_VS_CP_AT VARCHAR(255) NOT NULL, Rich_Web_VS_CP_CapS VARCHAR(255) NOT NULL, Rich_Web_VS_CP_CapEs VARCHAR(255) NOT NULL, Rich_Web_VS_CP_CapO VARCHAR(255) NOT NULL, Rich_Web_VS_CP_CapE VARCHAR(255) NOT NULL, Rich_Web_VS_CP_TFS VARCHAR(255) NOT NULL, Rich_Web_VS_CP_TFF VARCHAR(255) NOT NULL, Rich_Web_VS_CS_TBgC VARCHAR(255) NOT NULL, Rich_Web_VS_CS_TC VARCHAR(255) NOT NULL, Rich_Web_VS_CP_DFS VARCHAR(255) NOT NULL, Rich_Web_VS_CP_DFF VARCHAR(255) NOT NULL, Rich_Web_VS_CS_DBgC VARCHAR(255) NOT NULL, Rich_Web_VS_CS_DC VARCHAR(255) NOT NULL, Rich_Web_VS_CP_TiT VARCHAR(255) NOT NULL, Rich_Web_VS_CS_TiBgC VARCHAR(255) NOT NULL, Rich_Web_VS_CS_TiC VARCHAR(255) NOT NULL, Rich_Web_VS_CP_TiO VARCHAR(255) NOT NULL, Rich_Web_VS_CP_TiD VARCHAR(255) NOT NULL, Rich_Web_VS_CP_TiP VARCHAR(255) NOT NULL, Rich_Web_VS_CP_TiS VARCHAR(255) NOT NULL, Rich_Web_VS_CP_TiBS VARCHAR(255) NOT NULL, Rich_Web_VS_CP_TiBC VARCHAR(255) NOT NULL, Rich_Web_VS_CP_TiBSt VARCHAR(255) NOT NULL, Rich_Web_VS_CP_TiPos VARCHAR(255) NOT NULL, Rich_Web_VS_SL_Width VARCHAR(255) NOT NULL, Rich_Web_VS_SL_Height VARCHAR(255) NOT NULL, Rich_Web_VS_TitDesc_Type VARCHAR(255) NOT NULL, PRIMARY KEY (id))';
	$sql6 = 'CREATE TABLE IF NOT EXISTS ' .$table_name6 . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, RW_VS_ID VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Name VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Type VARCHAR(255) NOT NULL, Rich_Web_VS_SS_ED VARCHAR(255) NOT NULL, Rich_Web_VS_SS_PT VARCHAR(255) NOT NULL, Rich_Web_VS_SS_AP VARCHAR(255) NOT NULL, Rich_Web_VS_SS_Eff VARCHAR(255) NOT NULL, Rich_Web_VS_SS_W VARCHAR(255) NOT NULL, Rich_Web_VS_SS_H VARCHAR(255) NOT NULL, Rich_Web_VS_SS_BW VARCHAR(255) NOT NULL, Rich_Web_VS_SS_BS VARCHAR(255) NOT NULL, Rich_Web_VS_SS_BC VARCHAR(255) NOT NULL, Rich_Web_VS_SS_TShow VARCHAR(255) NOT NULL, Rich_Web_VS_SS_TFS VARCHAR(255) NOT NULL, Rich_Web_VS_SS_TFF VARCHAR(255) NOT NULL, Rich_Web_VS_SS_TC VARCHAR(255) NOT NULL, Rich_Web_VS_SS_TBgC VARCHAR(255) NOT NULL, Rich_Web_VS_SS_TPos VARCHAR(255) NOT NULL, Rich_Web_VS_SS_NShow VARCHAR(255) NOT NULL, Rich_Web_VS_SS_NC VARCHAR(255) NOT NULL, Rich_Web_VS_SS_NBgC VARCHAR(255) NOT NULL, Rich_Web_VS_SS_NS VARCHAR(255) NOT NULL, Rich_Web_VS_SS_NPos VARCHAR(255) NOT NULL, Rich_Web_VS_SS_PagShow VARCHAR(255) NOT NULL, Rich_Web_VS_SS_PagW VARCHAR(255) NOT NULL, Rich_Web_VS_SS_PagH VARCHAR(255) NOT NULL, Rich_Web_VS_SS_PagPB VARCHAR(255) NOT NULL, Rich_Web_VS_SS_PagBgC VARCHAR(255) NOT NULL, Rich_Web_VS_SS_PagBW VARCHAR(255) NOT NULL, Rich_Web_VS_SS_PagBS VARCHAR(255) NOT NULL, Rich_Web_VS_SS_PagBC VARCHAR(255) NOT NULL, Rich_Web_VS_SS_PagBR VARCHAR(255) NOT NULL, Rich_Web_VS_SS_PagHC VARCHAR(255) NOT NULL, Rich_Web_VS_SS_PagCC VARCHAR(255) NOT NULL, Rich_Web_VS_SS_PagPos VARCHAR(255) NOT NULL, Rich_Web_VS_SS_PIBgC VARCHAR(255) NOT NULL, Rich_Web_VS_SS_PIC VARCHAR(255) NOT NULL, Rich_Web_VS_SS_PIHBgC VARCHAR(255) NOT NULL, Rich_Web_VS_SS_PIHC VARCHAR(255) NOT NULL, Rich_Web_VS_SS_CIBgC VARCHAR(255) NOT NULL, Rich_Web_VS_SS_CIC VARCHAR(255) NOT NULL, Rich_Web_VS_SS_CIHBgC VARCHAR(255) NOT NULL, Rich_Web_VS_SS_CIHC VARCHAR(255) NOT NULL, PRIMARY KEY (id))';
	$sql7 = 'CREATE TABLE IF NOT EXISTS ' .$table_name7 . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, RW_VS_ID VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Name VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Type VARCHAR(255) NOT NULL, Rich_Web_VS_TS_W VARCHAR(255) NOT NULL, Rich_Web_VS_TS_H VARCHAR(255) NOT NULL, Rich_Web_VS_TS_BW VARCHAR(255) NOT NULL, Rich_Web_VS_TS_BS VARCHAR(255) NOT NULL, Rich_Web_VS_TS_BC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_BoxShShow VARCHAR(255) NOT NULL, Rich_Web_VS_TS_BoxShType VARCHAR(255) NOT NULL, Rich_Web_VS_TS_BoxSh VARCHAR(255) NOT NULL, Rich_Web_VS_TS_BoxShC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_IBgC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_IBW VARCHAR(255) NOT NULL, Rich_Web_VS_TS_IBS VARCHAR(255) NOT NULL, Rich_Web_VS_TS_IBC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_IBR VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TPos VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TBgC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TBW VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TBS VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TBC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TIH VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TIPB VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TIBW VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TIBS VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TIBC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TIBR VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TIBoxShShow VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TIBoxShType VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TIBoxSh VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TIBoxShC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TICBC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TICBS VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TICBoxShC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TIHBC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TIHBS VARCHAR(255) NOT NULL, Rich_Web_VS_TS_TIHBoxShC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_CS VARCHAR(255) NOT NULL, Rich_Web_VS_TS_PT VARCHAR(255) NOT NULL, Rich_Web_VS_TS_AP VARCHAR(255) NOT NULL, Rich_Web_VS_TS_PIBgC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_PIC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_PIHBgC VARCHAR(255) NOT NULL, Rich_Web_VS_TS_PIHC VARCHAR(255) NOT NULL, PRIMARY KEY (id))';
	$sql8 = 'CREATE TABLE IF NOT EXISTS ' .$table_name8 . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, RW_VS_ID VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Name VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Type VARCHAR(255) NOT NULL, Rich_Web_VC_Car_Bg_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Car_Border_Width VARCHAR(255) NOT NULL, Rich_Web_VC_Car_Border_Style VARCHAR(255) NOT NULL, Rich_Web_VC_Car_Border_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Car_Box_Shadow VARCHAR(255) NOT NULL, Rich_Web_VC_Car_Shadow_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Car_Count_Imgs VARCHAR(255) NOT NULL, Rich_Web_VC_Car_Imgs_Hover_Type VARCHAR(255) NOT NULL, Rich_Web_VC_Car_PBImgs VARCHAR(255) NOT NULL, Rich_Web_VC_Car_Icons_Type VARCHAR(255) NOT NULL, Rich_Web_VC_Car_Icons_Size VARCHAR(255) NOT NULL, Rich_Web_VC_Overlay_Bg_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Popup_Bg_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Popup_Border_Width VARCHAR(255) NOT NULL, Rich_Web_VC_Popup_Border_Style VARCHAR(255) NOT NULL, Rich_Web_VC_Popup_Border_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Popup_Box_Shadow VARCHAR(255) NOT NULL, Rich_Web_VC_Popup_Shadow_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Title_Font_Size VARCHAR(255) NOT NULL, Rich_Web_VC_Title_Font_Family VARCHAR(255) NOT NULL, Rich_Web_VC_Title_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Title_Text_Align VARCHAR(255) NOT NULL, Rich_Web_VC_Desc_Bg_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Desc_Font_Size VARCHAR(255) NOT NULL, Rich_Web_VC_Desc_Font_Family VARCHAR(255) NOT NULL, Rich_Web_VC_Desc_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Desc_Text_Align VARCHAR(255) NOT NULL, Rich_Web_VC_Link_Font_Size VARCHAR(255) NOT NULL, Rich_Web_VC_Link_Font_Family VARCHAR(255) NOT NULL, Rich_Web_VC_Link_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Link_Bg_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Link_Border_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Link_Border_Width VARCHAR(255) NOT NULL, Rich_Web_VC_Link_Border_Style VARCHAR(255) NOT NULL, Rich_Web_VC_Link_Hov_Bg_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Link_Hov_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Link_Hov_Border_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Popup_Icons_Size VARCHAR(255) NOT NULL, Rich_Web_VC_Popup_Icons_Color VARCHAR(255) NOT NULL, Rich_Web_VC_Popup_Icons_Type VARCHAR(255) NOT NULL, Rich_Web_VC_Link_Text VARCHAR(255) NOT NULL, Rich_Web_VC_Link_Border_Radius VARCHAR(255) NOT NULL, PRIMARY KEY (id))';
	$sql9 = 'CREATE TABLE IF NOT EXISTS ' .$table_name9 . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, RW_VS_ID VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Name VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Type VARCHAR(255) NOT NULL, Rich_Web_SVS_W VARCHAR(255) NOT NULL, Rich_Web_SVS_PT VARCHAR(255) NOT NULL, Rich_Web_SVS_CS VARCHAR(255) NOT NULL, Rich_Web_SVS_BW VARCHAR(255) NOT NULL, Rich_Web_SVS_BS VARCHAR(255) NOT NULL, Rich_Web_SVS_BC VARCHAR(255) NOT NULL, Rich_Web_SVS_BoxShShow VARCHAR(255) NOT NULL, Rich_Web_SVS_BoxShType VARCHAR(255) NOT NULL, Rich_Web_SVS_BoxSh VARCHAR(255) NOT NULL, Rich_Web_SVS_BoxShC VARCHAR(255) NOT NULL, Rich_Web_SVS_Nav_Show VARCHAR(255) NOT NULL, Rich_Web_SVS_Nav_W VARCHAR(255) NOT NULL, Rich_Web_SVS_Nav_H VARCHAR(255) NOT NULL, Rich_Web_SVS_Nav_BW VARCHAR(255) NOT NULL, Rich_Web_SVS_Nav_BS VARCHAR(255) NOT NULL, Rich_Web_SVS_Nav_BC VARCHAR(255) NOT NULL, Rich_Web_SVS_Nav_BR VARCHAR(255) NOT NULL, Rich_Web_SVS_Nav_PB VARCHAR(255) NOT NULL, Rich_Web_SVS_Nav_C VARCHAR(255) NOT NULL, Rich_Web_SVS_Nav_CC VARCHAR(255) NOT NULL, Rich_Web_SVS_Nav_HC VARCHAR(255) NOT NULL, Rich_Web_SVS_Nav_Pos VARCHAR(255) NOT NULL, Rich_Web_SVS_T_Show VARCHAR(255) NOT NULL, Rich_Web_SVS_TBgC VARCHAR(255) NOT NULL, Rich_Web_SVS_TC VARCHAR(255) NOT NULL, Rich_Web_SVS_TFS VARCHAR(255) NOT NULL, Rich_Web_SVS_TFF VARCHAR(255) NOT NULL, Rich_Web_SVS_D_Show VARCHAR(255) NOT NULL, Rich_Web_SVS_DC VARCHAR(255) NOT NULL, Rich_Web_SVS_DFS VARCHAR(255) NOT NULL, Rich_Web_SVS_DFF VARCHAR(255) NOT NULL, Rich_Web_SVS_LC VARCHAR(255) NOT NULL, Rich_Web_SVS_LFS VARCHAR(255) NOT NULL, Rich_Web_SVS_LFF VARCHAR(255) NOT NULL, Rich_Web_SVS_LHC VARCHAR(255) NOT NULL, Rich_Web_SVS_Arr_Show VARCHAR(255) NOT NULL, Rich_Web_SVS_Arr_Type VARCHAR(255) NOT NULL, Rich_Web_SVS_Arr_S VARCHAR(255) NOT NULL, Rich_Web_SVS_Arr_C VARCHAR(255) NOT NULL, Rich_Web_SVS_Arr_BgC VARCHAR(255) NOT NULL, Rich_Web_SVS_Arr_BW VARCHAR(255) NOT NULL, Rich_Web_SVS_Arr_BS VARCHAR(255) NOT NULL, Rich_Web_SVS_Arr_BC VARCHAR(255) NOT NULL, Rich_Web_SVS_Arr_BR VARCHAR(255) NOT NULL, Rich_Web_SVS_PIC VARCHAR(255) NOT NULL, Rich_Web_SVS_PIBgC VARCHAR(255) NOT NULL, Rich_Web_SVS_PIBR VARCHAR(255) NOT NULL, Rich_Web_SVS_PIHC VARCHAR(255) NOT NULL, Rich_Web_SVS_PIHBgC VARCHAR(255) NOT NULL,	Rich_Web_SVS_Eff VARCHAR(255) NOT NULL, Rich_Web_SVS_LText VARCHAR(255) NOT NULL, PRIMARY KEY (id))';
	$sql10 = 'CREATE TABLE IF NOT EXISTS ' .$table_name10 . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, RW_VS_ID VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Name VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Type VARCHAR(255) NOT NULL, Rich_Web_VTVS_AP VARCHAR(255) NOT NULL, Rich_Web_VTVS_APS VARCHAR(255) NOT NULL, Rich_Web_VTVS_APEff VARCHAR(255) NOT NULL, Rich_Web_VTVS_CS VARCHAR(255) NOT NULL, Rich_Web_VTVS_PT VARCHAR(255) NOT NULL, Rich_Web_VTVS_ArrSt VARCHAR(255) NOT NULL, Rich_Web_VTVS_BgC VARCHAR(255) NOT NULL, Rich_Web_VTVS_H VARCHAR(255) NOT NULL, Rich_Web_VTVS_BW VARCHAR(255) NOT NULL, Rich_Web_VTVS_BS VARCHAR(255) NOT NULL, Rich_Web_VTVS_BC VARCHAR(255) NOT NULL, Rich_Web_VTVS_BoxShShow VARCHAR(255) NOT NULL, Rich_Web_VTVS_BoxShType VARCHAR(255) NOT NULL, Rich_Web_VTVS_BoxSh VARCHAR(255) NOT NULL, Rich_Web_VTVS_BoxShC VARCHAR(255) NOT NULL, Rich_Web_VTVS_TShow VARCHAR(255) NOT NULL, Rich_Web_VTVS_TFS VARCHAR(255) NOT NULL, Rich_Web_VTVS_TFF VARCHAR(255) NOT NULL, Rich_Web_VTVS_TC VARCHAR(255) NOT NULL, Rich_Web_VTVS_TBgC VARCHAR(255) NOT NULL, Rich_Web_VTVS_TPos VARCHAR(255) NOT NULL, Rich_Web_VTVS_Th_BW VARCHAR(255) NOT NULL, Rich_Web_VTVS_Th_BS VARCHAR(255) NOT NULL, Rich_Web_VTVS_Th_BC VARCHAR(255) NOT NULL, Rich_Web_VTVS_Th_BR VARCHAR(255) NOT NULL, Rich_Web_VTVS_Th_HBC VARCHAR(255) NOT NULL,	Rich_Web_VTVS_LC VARCHAR(255) NOT NULL, Rich_Web_VTVS_LBgC VARCHAR(255) NOT NULL, Rich_Web_VTVS_LFS VARCHAR(255) NOT NULL, Rich_Web_VTVS_LHC VARCHAR(255) NOT NULL, Rich_Web_VTVS_LHBgC VARCHAR(255) NOT NULL, Rich_Web_VTVS_LPos VARCHAR(255) NOT NULL, Rich_Web_VTVS_LType VARCHAR(255) NOT NULL, Rich_Web_VTVS_PC VARCHAR(255) NOT NULL, Rich_Web_VTVS_PBgC VARCHAR(255) NOT NULL, Rich_Web_VTVS_PFS VARCHAR(255) NOT NULL, Rich_Web_VTVS_PHC VARCHAR(255) NOT NULL, Rich_Web_VTVS_PHBgC VARCHAR(255) NOT NULL, Rich_Web_VTVS_PPos VARCHAR(255) NOT NULL, Rich_Web_VTVS_PType VARCHAR(255) NOT NULL, Rich_Web_VTVS_ArrShow VARCHAR(255) NOT NULL, Rich_Web_VTVS_ArrType VARCHAR(255) NOT NULL, Rich_Web_VTVS_ArrFS VARCHAR(255) NOT NULL, Rich_Web_VTVS_ArrPos VARCHAR(255) NOT NULL, Rich_Web_VTVS_ArrC VARCHAR(255) NOT NULL, PRIMARY KEY (id))';
	$sql11 = 'CREATE TABLE IF NOT EXISTS ' .$table_name11 . '( id INTEGER(10) UNSIGNED AUTO_INCREMENT, RW_VS_ID VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Name VARCHAR(255) NOT NULL, Rich_Web_VSlider_Option_Type VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Loop VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Cols VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Speed VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_AP VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_EH VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_PB VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Car VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_NP_Show VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_NP_NText VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_NP_PText VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_NP_C VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_NP_BgC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_NP_FS VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_NP_FF VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_NP_BW VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_NP_BS VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_NP_BC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_NP_BR VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_NP_HC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_NP_HBgC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Cols_BgC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Cols_BoxShC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Cols_VSEff VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Cols_StShC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Cols_VHEff VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Cols_HShC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_TC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_TFS VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_TFF VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_DShow VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_DC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_DFS VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_DFF VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_LText VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_LC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_LFS VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_LFF VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_LHC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_PText VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_PBgC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_PC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_PFS VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_PFF VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_PHC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_PHBgC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Pop_OvC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Pop_BW VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Pop_BS VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Pop_BC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Pop_BoxShShow VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Pop_BoxShType VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Pop_BoxSh VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Pop_BoxShC VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Pop_CIType VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Pop_CIS VARCHAR(255) NOT NULL, Rich_Web_VS_HPS_Pop_CIC VARCHAR(255) NOT NULL, PRIMARY KEY (id))';

	require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
	dbDelta($sql);
	dbDelta($sql1);
	dbDelta($sql2);
	dbDelta($sql3);
	dbDelta($sql4);
	dbDelta($sql5);
	dbDelta($sql6);
	dbDelta($sql7);
	dbDelta($sql8);
	dbDelta($sql9);
	dbDelta($sql10);
	dbDelta($sql11);

	$sqla   = 'ALTER TABLE ' . $table_name . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
	$sqla1  = 'ALTER TABLE ' . $table_name1 . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
	$sqla2  = 'ALTER TABLE ' . $table_name2 . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
	$sqla3  = 'ALTER TABLE ' . $table_name3 . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
	$sqla4  = 'ALTER TABLE ' . $table_name4 . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
	$sqla5  = 'ALTER TABLE ' . $table_name5 . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
	$sqla6  = 'ALTER TABLE ' . $table_name6 . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
	$sqla7  = 'ALTER TABLE ' . $table_name7 . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
	$sqla8  = 'ALTER TABLE ' . $table_name8 . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
	$sqla9  = 'ALTER TABLE ' . $table_name9 . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
	$sqla10 = 'ALTER TABLE ' . $table_name10 . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
	$sqla11 = 'ALTER TABLE ' . $table_name11 . ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';

	$wpdb->query($sqla);
	$wpdb->query($sqla1);
	$wpdb->query($sqla2);
	$wpdb->query($sqla3);
	$wpdb->query($sqla4);
	$wpdb->query($sqla5);
	$wpdb->query($sqla6);
	$wpdb->query($sqla7);
	$wpdb->query($sqla8);
	$wpdb->query($sqla9);
	$wpdb->query($sqla10);
	$wpdb->query($sqla11);

	$Rich_Web_Fonts = array('Abadi MT Condensed Light','Aharoni','Aldhabi','Andalus','Angsana New','AngsanaUPC','Aparajita','Arabic Typesetting','Arial','Arial Black', 'Batang','BatangChe','Browallia New','BrowalliaUPC','Calibri','Calibri Light','Calisto MT','Cambria','Candara','Century Gothic','Comic Sans MS','Consolas', 'Constantia','Copperplate Gothic','Copperplate Gothic Light','Corbel','Cordia New','CordiaUPC','Courier New','DaunPenh','David','DFKai-SB','DilleniaUPC', 'DokChampa','Dotum','DotumChe','Ebrima','Estrangelo Edessa','EucrosiaUPC','Euphemia','FangSong','Franklin Gothic Medium','FrankRuehl','FreesiaUPC','Gabriola', 'Gadugi','Gautami','Georgia','Gisha','Gulim','GulimChe','Gungsuh','GungsuhChe','Impact','IrisUPC','Iskoola Pota','JasmineUPC','KaiTi','Kalinga','Kartika', 'Khmer UI','KodchiangUPC','Kokila','Lao UI','Latha','Leelawadee','Levenim MT','LilyUPC','Lucida Console','Lucida Handwriting Italic','Lucida Sans Unicode', 'Malgun Gothic','Mangal','Manny ITC','Marlett','Meiryo','Meiryo UI','Microsoft Himalaya','Microsoft JhengHei','Microsoft JhengHei UI','Microsoft New Tai Lue', 'Microsoft PhagsPa','Microsoft Sans Serif','Microsoft Tai Le','Microsoft Uighur','Microsoft YaHei','Microsoft YaHei UI','Microsoft Yi Baiti','MingLiU_HKSCS', 'MingLiU_HKSCS-ExtB','Miriam','Mongolian Baiti','MoolBoran','MS UI Gothic','MV Boli','Myanmar Text','Narkisim','Nirmala UI','News Gothic MT','NSimSun','Nyala', 'Palatino Linotype','Plantagenet Cherokee','Raavi','Rod','Sakkal Majalla','Segoe Print','Segoe Script','Segoe UI Symbol','Shonar Bangla','Shruti','SimHei','SimKai', 'Simplified Arabic','SimSun','SimSun-ExtB','Sylfaen','Tahoma','Times New Roman','Traditional Arabic','Trebuchet MS','Tunga','Utsaah','Vani','Vijaya');
		
	$Rich_WebFontCount=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name WHERE id>%d",0));
	if(count($Rich_WebFontCount)==0)
	{
		foreach ($Rich_Web_Fonts as $JFonts) 
		{
			$wpdb->query($wpdb->prepare("INSERT INTO $table_name (id, Font_family) VALUES (%d, %s)", '', $JFonts));
		}
	}

	$Rich_Web_VS1=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name5 WHERE id>%d",0));
	if(count($Rich_Web_VS1)==0)
	{
		$wpdb->query($wpdb->prepare("INSERT INTO $table_name4 (id, slider_vid_name, slider_Vid_type) VALUES (%d, %s, %s)", '', 'Content Slider', 'Content Slider'));

		$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Content Slider'));

		$wpdb->query($wpdb->prepare("INSERT INTO $table_name5 (id, RW_VS_ID, Rich_Web_VSlider_Option_Name, Rich_Web_VSlider_Option_Type, Rich_Web_VS_CP_CE, Rich_Web_VS_CP_EE, Rich_Web_VS_CP_S, Rich_Web_VS_CP_BlC, Rich_Web_VS_CP_BlR, Rich_Web_VS_CP_AS, Rich_Web_VS_CP_PT, Rich_Web_VS_CP_SS, Rich_Web_VS_CS_AP, Rich_Web_VS_CS_HP, Rich_Web_VS_CS_RS, Rich_Web_VS_CS_BSC, Rich_Web_VS_CP_BW, Rich_Web_VS_CP_BS, Rich_Web_VS_CS_BC, Rich_Web_VS_CP_BR, Rich_Web_VS_CS_CN, Rich_Web_VS_CS_NPB, Rich_Web_VS_CP_NO, Rich_Web_VS_CS_NT, Rich_Web_VS_CP_NT, Rich_Web_VS_CP_AT, Rich_Web_VS_CP_CapS, Rich_Web_VS_CP_CapEs, Rich_Web_VS_CP_CapO, Rich_Web_VS_CP_CapE, Rich_Web_VS_CP_TFS, Rich_Web_VS_CP_TFF, Rich_Web_VS_CS_TBgC, Rich_Web_VS_CS_TC, Rich_Web_VS_CP_DFS, Rich_Web_VS_CP_DFF, Rich_Web_VS_CS_DBgC, Rich_Web_VS_CS_DC, Rich_Web_VS_CP_TiT, Rich_Web_VS_CS_TiBgC, Rich_Web_VS_CS_TiC, Rich_Web_VS_CP_TiO, Rich_Web_VS_CP_TiD, Rich_Web_VS_CP_TiP, Rich_Web_VS_CP_TiS, Rich_Web_VS_CP_TiBS, Rich_Web_VS_CP_TiBC, Rich_Web_VS_CP_TiBSt, Rich_Web_VS_CP_TiPos, Rich_Web_VS_SL_Width, Rich_Web_VS_SL_Height, Rich_Web_VS_TitDesc_Type) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, 'Content Slider', 'Content Slider', 'random', 'swing', '10', '20', '16', '800', '8', '10', 'on', 'on', 'on', '#666666', '0', 'solid', '#ffffff', '1', 'on', 'on', '50', 'on', '1', '1', '500', 'swing', '50', 'expanddown', '18', 'Aldhabi', '#000000', '#ffffff', '18', 'Aldhabi', 'rgba(221,51,51,0.9)', '#ffffff', '360bar', '#ffffff', '#000000', '50', '16', '5', '6', '6', '#dd3333', 'solid', 'top-left', '700', '400', 'type1'));

		$wpdb->query($wpdb->prepare("INSERT INTO $table_name4 (id, slider_vid_name, slider_Vid_type) VALUES (%d, %s, %s)", '', 'Content Slider 2', 'Content Slider'));

		$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Content Slider 2'));

		$wpdb->query($wpdb->prepare("INSERT INTO $table_name5 (id, RW_VS_ID, Rich_Web_VSlider_Option_Name, Rich_Web_VSlider_Option_Type, Rich_Web_VS_CP_CE, Rich_Web_VS_CP_EE, Rich_Web_VS_CP_S, Rich_Web_VS_CP_BlC, Rich_Web_VS_CP_BlR, Rich_Web_VS_CP_AS, Rich_Web_VS_CP_PT, Rich_Web_VS_CP_SS, Rich_Web_VS_CS_AP, Rich_Web_VS_CS_HP, Rich_Web_VS_CS_RS, Rich_Web_VS_CS_BSC, Rich_Web_VS_CP_BW, Rich_Web_VS_CP_BS, Rich_Web_VS_CS_BC, Rich_Web_VS_CP_BR, Rich_Web_VS_CS_CN, Rich_Web_VS_CS_NPB, Rich_Web_VS_CP_NO, Rich_Web_VS_CS_NT, Rich_Web_VS_CP_NT, Rich_Web_VS_CP_AT, Rich_Web_VS_CP_CapS, Rich_Web_VS_CP_CapEs, Rich_Web_VS_CP_CapO, Rich_Web_VS_CP_CapE, Rich_Web_VS_CP_TFS, Rich_Web_VS_CP_TFF, Rich_Web_VS_CS_TBgC, Rich_Web_VS_CS_TC, Rich_Web_VS_CP_DFS, Rich_Web_VS_CP_DFF, Rich_Web_VS_CS_DBgC, Rich_Web_VS_CS_DC, Rich_Web_VS_CP_TiT, Rich_Web_VS_CS_TiBgC, Rich_Web_VS_CS_TiC, Rich_Web_VS_CP_TiO, Rich_Web_VS_CP_TiD, Rich_Web_VS_CP_TiP, Rich_Web_VS_CP_TiS, Rich_Web_VS_CP_TiBS, Rich_Web_VS_CP_TiBC, Rich_Web_VS_CP_TiBSt, Rich_Web_VS_CP_TiPos, Rich_Web_VS_SL_Width, Rich_Web_VS_SL_Height, Rich_Web_VS_TitDesc_Type) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, 'Content Slider 2', 'Content Slider', 'random', 'easeInCirc', '10', '20', '16', '800', '8', '11', 'on', 'on', 'on', '#bcbcbc', '0', 'solid', '#ffffff', '1', 'on', 'on', '50', '', '1', '1', '500', 'swing', '50', 'expanddown', '18', 'Aldhabi', '#000000', '#ffffff', '18', 'Aldhabi', 'rgba(255,255,255,0.85)', '#000000', 'pie', '#ffffff', '#000000', '50', '14', '4', '6', '6', '#1e73be', 'solid', 'top-left', '700', '400', 'type6'));
	}

	$Rich_Web_VS2=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name6 WHERE id>%d",0));
	if(count($Rich_Web_VS2)==0)
	{
		$wpdb->query($wpdb->prepare("INSERT INTO $table_name4 (id, slider_vid_name, slider_Vid_type) VALUES (%d, %s, %s)", '', 'Slick Slider', 'Slick Slider'));

		$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Slick Slider'));

		$wpdb->query($wpdb->prepare("INSERT INTO $table_name6 (id, RW_VS_ID, Rich_Web_VSlider_Option_Name, Rich_Web_VSlider_Option_Type, Rich_Web_VS_SS_ED, Rich_Web_VS_SS_PT, Rich_Web_VS_SS_AP, Rich_Web_VS_SS_Eff, Rich_Web_VS_SS_W, Rich_Web_VS_SS_H, Rich_Web_VS_SS_BW, Rich_Web_VS_SS_BS, Rich_Web_VS_SS_BC, Rich_Web_VS_SS_TShow, Rich_Web_VS_SS_TFS, Rich_Web_VS_SS_TFF, Rich_Web_VS_SS_TC, Rich_Web_VS_SS_TBgC, Rich_Web_VS_SS_TPos, Rich_Web_VS_SS_NShow, Rich_Web_VS_SS_NC, Rich_Web_VS_SS_NBgC, Rich_Web_VS_SS_NS, Rich_Web_VS_SS_NPos, Rich_Web_VS_SS_PagShow, Rich_Web_VS_SS_PagW, Rich_Web_VS_SS_PagH, Rich_Web_VS_SS_PagPB, Rich_Web_VS_SS_PagBgC, Rich_Web_VS_SS_PagBW, Rich_Web_VS_SS_PagBS, Rich_Web_VS_SS_PagBC, Rich_Web_VS_SS_PagBR, Rich_Web_VS_SS_PagHC, Rich_Web_VS_SS_PagCC, Rich_Web_VS_SS_PagPos, Rich_Web_VS_SS_PIBgC, Rich_Web_VS_SS_PIC, Rich_Web_VS_SS_PIHBgC, Rich_Web_VS_SS_PIHC, Rich_Web_VS_SS_CIBgC, Rich_Web_VS_SS_CIC, Rich_Web_VS_SS_CIHBgC, Rich_Web_VS_SS_CIHC) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, 'Slick Slider', 'Slick Slider', '4', '400', 'on', 'zoomOut,zoomIn,panUp,panDown,panLeft,panRight,diagTopLeftToBottomRight,diagTopRightToBottomLeft,diagBottomRightToTopLeft,diagBottomLeftToTopRight', '700', '420', '10', 'solid', '#ffffff', 'on', '19', 'Arial', '#ffffff', 'rgba(0,0,0,0.8)', 'bottom', 'on', '#000000', '#ffffff', '18', 'bottom', 'on', '14', '8', '4', '#ffffff', '1', 'solid', '#cccccc', '0', '#ffffff', 'rgba(221,51,51,0.76)', 'center', 'rgba(255,255,255,0.6)', '#dd3333', 'rgba(221,51,51,0.8)', '#ffffff', 'rgba(0,0,0,0.4)', '#ffffff', 'rgba(255,255,255,0.7)', '#ffffff'));

		$wpdb->query($wpdb->prepare("INSERT INTO $table_name4 (id, slider_vid_name, slider_Vid_type) VALUES (%d, %s, %s)", '', 'Slick Slider 2', 'Slick Slider'));

		$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Slick Slider 2'));

		$wpdb->query($wpdb->prepare("INSERT INTO $table_name6 (id, RW_VS_ID, Rich_Web_VSlider_Option_Name, Rich_Web_VSlider_Option_Type, Rich_Web_VS_SS_ED, Rich_Web_VS_SS_PT, Rich_Web_VS_SS_AP, Rich_Web_VS_SS_Eff, Rich_Web_VS_SS_W, Rich_Web_VS_SS_H, Rich_Web_VS_SS_BW, Rich_Web_VS_SS_BS, Rich_Web_VS_SS_BC, Rich_Web_VS_SS_TShow, Rich_Web_VS_SS_TFS, Rich_Web_VS_SS_TFF, Rich_Web_VS_SS_TC, Rich_Web_VS_SS_TBgC, Rich_Web_VS_SS_TPos, Rich_Web_VS_SS_NShow, Rich_Web_VS_SS_NC, Rich_Web_VS_SS_NBgC, Rich_Web_VS_SS_NS, Rich_Web_VS_SS_NPos, Rich_Web_VS_SS_PagShow, Rich_Web_VS_SS_PagW, Rich_Web_VS_SS_PagH, Rich_Web_VS_SS_PagPB, Rich_Web_VS_SS_PagBgC, Rich_Web_VS_SS_PagBW, Rich_Web_VS_SS_PagBS, Rich_Web_VS_SS_PagBC, Rich_Web_VS_SS_PagBR, Rich_Web_VS_SS_PagHC, Rich_Web_VS_SS_PagCC, Rich_Web_VS_SS_PagPos, Rich_Web_VS_SS_PIBgC, Rich_Web_VS_SS_PIC, Rich_Web_VS_SS_PIHBgC, Rich_Web_VS_SS_PIHC, Rich_Web_VS_SS_CIBgC, Rich_Web_VS_SS_CIC, Rich_Web_VS_SS_CIHBgC, Rich_Web_VS_SS_CIHC) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, 'Slick Slider 2', 'Slick Slider', '4', '400', 'on', 'zoomOut,zoomIn,panUp,panDown,panLeft,panRight,diagTopLeftToBottomRight,diagTopRightToBottomLeft,diagBottomRightToTopLeft,diagBottomLeftToTopRight', '700', '420', '10', 'solid', '#ffffff', 'on', '23', 'Vijaya', '#ffffff', 'rgba(0,0,0,0.6)', 'top', 'on', '#ffffff', 'rgba(0,0,0,0.6)', '13', 'bottom', 'on', '15', '10', '4', '#009491', '1', 'solid', '#cccccc', '20', '#ffffff', 'rgba(0,98,155,0.7)', 'center', 'rgba(221,51,51,0.45)', '#ffffff', 'rgba(221,51,51,0.76)', '#ffffff', 'rgba(0,0,0,0.4)', '#ffffff', 'rgba(255,255,255,0.7)', '#ffffff'));
	}

	$Rich_Web_VS3=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name7 WHERE id>%d",0));
	if(count($Rich_Web_VS3)==0)
	{
		$wpdb->query($wpdb->prepare("INSERT INTO $table_name4 (id, slider_vid_name, slider_Vid_type) VALUES (%d, %s, %s)", '', 'Thumbnails Slider', 'Thumbnails Slider'));

		$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Thumbnails Slider'));

		$wpdb->query($wpdb->prepare("INSERT INTO $table_name7 (id, RW_VS_ID, Rich_Web_VSlider_Option_Name, Rich_Web_VSlider_Option_Type, Rich_Web_VS_TS_W, Rich_Web_VS_TS_H, Rich_Web_VS_TS_BW, Rich_Web_VS_TS_BS, Rich_Web_VS_TS_BC, Rich_Web_VS_TS_BoxShShow, Rich_Web_VS_TS_BoxShType, Rich_Web_VS_TS_BoxSh, Rich_Web_VS_TS_BoxShC, Rich_Web_VS_TS_IBgC, Rich_Web_VS_TS_IBW, Rich_Web_VS_TS_IBS, Rich_Web_VS_TS_IBC, Rich_Web_VS_TS_IBR, Rich_Web_VS_TS_TPos, Rich_Web_VS_TS_TBgC, Rich_Web_VS_TS_TBW, Rich_Web_VS_TS_TBS, Rich_Web_VS_TS_TBC, Rich_Web_VS_TS_TIH, Rich_Web_VS_TS_TIPB, Rich_Web_VS_TS_TIBW, Rich_Web_VS_TS_TIBS, Rich_Web_VS_TS_TIBC, Rich_Web_VS_TS_TIBR, Rich_Web_VS_TS_TIBoxShShow, Rich_Web_VS_TS_TIBoxShType, Rich_Web_VS_TS_TIBoxSh, Rich_Web_VS_TS_TIBoxShC, Rich_Web_VS_TS_TICBC, Rich_Web_VS_TS_TICBS, Rich_Web_VS_TS_TICBoxShC, Rich_Web_VS_TS_TIHBC, Rich_Web_VS_TS_TIHBS, Rich_Web_VS_TS_TIHBoxShC, Rich_Web_VS_TS_CS, Rich_Web_VS_TS_PT, Rich_Web_VS_TS_AP, Rich_Web_VS_TS_PIBgC, Rich_Web_VS_TS_PIC, Rich_Web_VS_TS_PIHBgC, Rich_Web_VS_TS_PIHC) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, 'Thumbnails Slider', 'Thumbnails Slider', '700', '350', '2', 'solid', '#ffffff', 'on', 'on', '30', '#a3a3a3', 'rgba(255,255,255,0.7)', '2', 'solid', 'rgba(255,255,255,0.7)', '6', 'bottom', '#000000', '1', 'solid', '#ffffff', '60', '5', '1', 'solid', '#ffffff', '3', 'on', '', '10', '#ffffff', '#707070', 'solid', '#ffffff', '#ffffff', 'solid', '#ffffff', '400', '5', '', 'rgba(255,255,255,0.7)', '#dd3333', 'rgba(221,51,51,0.7)', '#ffffff'));

		$wpdb->query($wpdb->prepare("INSERT INTO $table_name4 (id, slider_vid_name, slider_Vid_type) VALUES (%d, %s, %s)", '', 'Thumbnails Slider 2', 'Thumbnails Slider'));

		$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Thumbnails Slider 2'));

		$wpdb->query($wpdb->prepare("INSERT INTO $table_name7 (id, RW_VS_ID, Rich_Web_VSlider_Option_Name, Rich_Web_VSlider_Option_Type, Rich_Web_VS_TS_W, Rich_Web_VS_TS_H, Rich_Web_VS_TS_BW, Rich_Web_VS_TS_BS, Rich_Web_VS_TS_BC, Rich_Web_VS_TS_BoxShShow, Rich_Web_VS_TS_BoxShType, Rich_Web_VS_TS_BoxSh, Rich_Web_VS_TS_BoxShC, Rich_Web_VS_TS_IBgC, Rich_Web_VS_TS_IBW, Rich_Web_VS_TS_IBS, Rich_Web_VS_TS_IBC, Rich_Web_VS_TS_IBR, Rich_Web_VS_TS_TPos, Rich_Web_VS_TS_TBgC, Rich_Web_VS_TS_TBW, Rich_Web_VS_TS_TBS, Rich_Web_VS_TS_TBC, Rich_Web_VS_TS_TIH, Rich_Web_VS_TS_TIPB, Rich_Web_VS_TS_TIBW, Rich_Web_VS_TS_TIBS, Rich_Web_VS_TS_TIBC, Rich_Web_VS_TS_TIBR, Rich_Web_VS_TS_TIBoxShShow, Rich_Web_VS_TS_TIBoxShType, Rich_Web_VS_TS_TIBoxSh, Rich_Web_VS_TS_TIBoxShC, Rich_Web_VS_TS_TICBC, Rich_Web_VS_TS_TICBS, Rich_Web_VS_TS_TICBoxShC, Rich_Web_VS_TS_TIHBC, Rich_Web_VS_TS_TIHBS, Rich_Web_VS_TS_TIHBoxShC, Rich_Web_VS_TS_CS, Rich_Web_VS_TS_PT, Rich_Web_VS_TS_AP, Rich_Web_VS_TS_PIBgC, Rich_Web_VS_TS_PIC, Rich_Web_VS_TS_PIHBgC, Rich_Web_VS_TS_PIHC) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, 'Thumbnails Slider 2', 'Thumbnails Slider', '700', '350', '3', 'solid', '#ffffff', 'on', '', '30', '#cccccc', 'rgba(255,255,255,0.7)', '2', 'solid', '#000000', '6', 'bottom', '#ffffff', '3', 'solid', '#ffffff', '50', '4', '2', 'solid', '#000000', '10', 'on', 'on', '1', '#ffffff', '#707070', 'solid', '#009491', '#ffffff', 'solid', '#ffffff', '400', '5', 'on', 'rgba(255,255,255,0.7)', '#dd3333', 'rgba(221,51,51,0.7)', '#ffffff'));
	}
	$Rich_Web_VS4=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name8 WHERE id>%d",0));
	if(count($Rich_Web_VS4)==0)
	{
		$wpdb->query($wpdb->prepare("INSERT INTO $table_name4 (id, slider_vid_name, slider_Vid_type) VALUES (%d, %s, %s)", '', 'Video Carousel/Content Popup 1', 'Video Carousel/Content Popup'));

		$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Video Carousel/Content Popup 1'));

		$wpdb->query($wpdb->prepare("INSERT INTO $table_name8 (id, RW_VS_ID, Rich_Web_VSlider_Option_Name, Rich_Web_VSlider_Option_Type, Rich_Web_VC_Car_Bg_Color, Rich_Web_VC_Car_Border_Width, Rich_Web_VC_Car_Border_Style, Rich_Web_VC_Car_Border_Color, Rich_Web_VC_Car_Box_Shadow, Rich_Web_VC_Car_Shadow_Color, Rich_Web_VC_Car_Count_Imgs, Rich_Web_VC_Car_Imgs_Hover_Type, Rich_Web_VC_Car_PBImgs, Rich_Web_VC_Car_Icons_Type, Rich_Web_VC_Car_Icons_Size, Rich_Web_VC_Overlay_Bg_Color, Rich_Web_VC_Popup_Bg_Color, Rich_Web_VC_Popup_Border_Width, Rich_Web_VC_Popup_Border_Style, Rich_Web_VC_Popup_Border_Color, Rich_Web_VC_Popup_Box_Shadow, Rich_Web_VC_Popup_Shadow_Color, Rich_Web_VC_Title_Font_Size, Rich_Web_VC_Title_Font_Family, Rich_Web_VC_Title_Color, Rich_Web_VC_Title_Text_Align, Rich_Web_VC_Desc_Bg_Color, Rich_Web_VC_Desc_Font_Size, Rich_Web_VC_Desc_Font_Family, Rich_Web_VC_Desc_Color, Rich_Web_VC_Desc_Text_Align, Rich_Web_VC_Link_Font_Size, Rich_Web_VC_Link_Font_Family, Rich_Web_VC_Link_Color, Rich_Web_VC_Link_Bg_Color, Rich_Web_VC_Link_Border_Color, Rich_Web_VC_Link_Border_Width, Rich_Web_VC_Link_Border_Style, Rich_Web_VC_Link_Hov_Bg_Color, Rich_Web_VC_Link_Hov_Color, Rich_Web_VC_Link_Hov_Border_Color, Rich_Web_VC_Popup_Icons_Size, Rich_Web_VC_Popup_Icons_Color, Rich_Web_VC_Popup_Icons_Type, Rich_Web_VC_Link_Text, Rich_Web_VC_Link_Border_Radius) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, 'Video Carousel/Content Popup 1', 'Video Carousel/Content Popup', '#ffffff', '0', 'solid', '#ffffff', '25', '#009491', '4', 'fImgH1', '5', '10', '25', 'rgba(255,255,255,0)', 'rgba(0,0,0,0.7)', '0', 'solid', '#ffffff', '25', '#000000', '24', 'Vijaya', '#ffffff', 'center', 'rgba(0,148,145,0)', '16', 'Aldhabi', '#ffffff', 'left', '15', 'Vijaya', '#000000', 'rgba(255,255,255,0.8)', '#ffffff', '1', 'solid', 'rgba(0,0,0,0.8)', '#ffffff', '#000000', '25', '#ffffff', 'rich_web-times-circle', 'View More', '0'));
		
		$wpdb->query($wpdb->prepare("INSERT INTO $table_name4 (id, slider_vid_name, slider_Vid_type) VALUES (%d, %s, %s)", '', 'Video Carousel/Content Popup 2', 'Video Carousel/Content Popup'));

		$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Video Carousel/Content Popup 2'));

		$wpdb->query($wpdb->prepare("INSERT INTO $table_name8 (id, RW_VS_ID, Rich_Web_VSlider_Option_Name, Rich_Web_VSlider_Option_Type, Rich_Web_VC_Car_Bg_Color, Rich_Web_VC_Car_Border_Width, Rich_Web_VC_Car_Border_Style, Rich_Web_VC_Car_Border_Color, Rich_Web_VC_Car_Box_Shadow, Rich_Web_VC_Car_Shadow_Color, Rich_Web_VC_Car_Count_Imgs, Rich_Web_VC_Car_Imgs_Hover_Type, Rich_Web_VC_Car_PBImgs, Rich_Web_VC_Car_Icons_Type, Rich_Web_VC_Car_Icons_Size, Rich_Web_VC_Overlay_Bg_Color, Rich_Web_VC_Popup_Bg_Color, Rich_Web_VC_Popup_Border_Width, Rich_Web_VC_Popup_Border_Style, Rich_Web_VC_Popup_Border_Color, Rich_Web_VC_Popup_Box_Shadow, Rich_Web_VC_Popup_Shadow_Color, Rich_Web_VC_Title_Font_Size, Rich_Web_VC_Title_Font_Family, Rich_Web_VC_Title_Color, Rich_Web_VC_Title_Text_Align, Rich_Web_VC_Desc_Bg_Color, Rich_Web_VC_Desc_Font_Size, Rich_Web_VC_Desc_Font_Family, Rich_Web_VC_Desc_Color, Rich_Web_VC_Desc_Text_Align, Rich_Web_VC_Link_Font_Size, Rich_Web_VC_Link_Font_Family, Rich_Web_VC_Link_Color, Rich_Web_VC_Link_Bg_Color, Rich_Web_VC_Link_Border_Color, Rich_Web_VC_Link_Border_Width, Rich_Web_VC_Link_Border_Style, Rich_Web_VC_Link_Hov_Bg_Color, Rich_Web_VC_Link_Hov_Color, Rich_Web_VC_Link_Hov_Border_Color, Rich_Web_VC_Popup_Icons_Size, Rich_Web_VC_Popup_Icons_Color, Rich_Web_VC_Popup_Icons_Type, Rich_Web_VC_Link_Text, Rich_Web_VC_Link_Border_Radius) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, 'Video Carousel/Content Popup 2', 'Video Carousel/Content Popup', '#ffffff', '5', 'solid', '#ffffff', '25', '#adadad', '4', 'fImgH1', '5', '10', '25', 'rgba(255,255,255,0)', '#ffffff', '0', 'solid', '#ffffff', '30', '#000000', '24', 'Vijaya', '#000000', 'center', '#ffffff', '16', 'Aldhabi', '#000000', 'left', '15', 'Vijaya', '#000000', 'rgba(255,255,255,0.8)', '#000000', '1', 'solid', 'rgba(0,0,0,0.8)', '#ffffff', '#000000', '25', '#000000', 'rich_web-times-circle', 'View More', '0'));
	}
	$Rich_Web_VS5=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name9 WHERE id>%d",0));
	if(count($Rich_Web_VS5)==0)
	{
		$wpdb->query($wpdb->prepare("INSERT INTO $table_name4 (id, slider_vid_name, slider_Vid_type) VALUES (%d, %s, %s)", '', 'Simple Video Slider 1', 'Simple Video Slider'));

		$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Simple Video Slider 1'));

		$wpdb->query($wpdb->prepare("INSERT INTO $table_name9 (id, RW_VS_ID, Rich_Web_VSlider_Option_Name, Rich_Web_VSlider_Option_Type, Rich_Web_SVS_W, Rich_Web_SVS_PT, Rich_Web_SVS_CS, Rich_Web_SVS_BW, Rich_Web_SVS_BS, Rich_Web_SVS_BC, Rich_Web_SVS_BoxShShow, Rich_Web_SVS_BoxShType, Rich_Web_SVS_BoxSh, Rich_Web_SVS_BoxShC, Rich_Web_SVS_Nav_Show, Rich_Web_SVS_Nav_W, Rich_Web_SVS_Nav_H, Rich_Web_SVS_Nav_BW, Rich_Web_SVS_Nav_BS, Rich_Web_SVS_Nav_BC, Rich_Web_SVS_Nav_BR, Rich_Web_SVS_Nav_PB, Rich_Web_SVS_Nav_C, Rich_Web_SVS_Nav_CC, Rich_Web_SVS_Nav_HC, Rich_Web_SVS_Nav_Pos, Rich_Web_SVS_T_Show, Rich_Web_SVS_TBgC, Rich_Web_SVS_TC, Rich_Web_SVS_TFS, Rich_Web_SVS_TFF, Rich_Web_SVS_D_Show, Rich_Web_SVS_DC, Rich_Web_SVS_DFS, Rich_Web_SVS_DFF, Rich_Web_SVS_LC, Rich_Web_SVS_LFS, Rich_Web_SVS_LFF, Rich_Web_SVS_LHC, Rich_Web_SVS_Arr_Show, Rich_Web_SVS_Arr_Type, Rich_Web_SVS_Arr_S, Rich_Web_SVS_Arr_C, Rich_Web_SVS_Arr_BgC, Rich_Web_SVS_Arr_BW, Rich_Web_SVS_Arr_BS, Rich_Web_SVS_Arr_BC, Rich_Web_SVS_Arr_BR, Rich_Web_SVS_PIC, Rich_Web_SVS_PIBgC, Rich_Web_SVS_PIBR, Rich_Web_SVS_PIHC, Rich_Web_SVS_PIHBgC, Rich_Web_SVS_Eff, Rich_Web_SVS_LText) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, 'Simple Video Slider 1', 'Simple Video Slider', '750', '5', '1000', '4', 'solid', '#ffffff', 'on', 'on', '50', '#8c8c8c', 'on', '10', '10', '0', 'solid', '#000000', '20', '2', '#000000', '#ffffff', '#ffffff', 'top', 'on', 'rgba(255,255,255,0.5)', '#000000', '25', 'Gabriola', 'on', '#000000', '20', 'Gabriola', '#000000', '14', 'Arial', '#8c8c8c', 'on', 'arrow-circle', '30', 'rgba(0,0,0,0.8)', 'rgba(255,255,255,0.8)', '0', 'solid', '#ffffff', '100', 'rgba(221,51,51,0.69)', 'rgba(255,255,255,0.7)', '15', '#dd3333', 'rgba(255,255,255,0.7)', 'slide', 'View More'));

		$wpdb->query($wpdb->prepare("INSERT INTO $table_name4 (id, slider_vid_name, slider_Vid_type) VALUES (%d, %s, %s)", '', 'Simple Video Slider 2', 'Simple Video Slider'));

		$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Simple Video Slider 2'));

		$wpdb->query($wpdb->prepare("INSERT INTO $table_name9 (id, RW_VS_ID, Rich_Web_VSlider_Option_Name, Rich_Web_VSlider_Option_Type, Rich_Web_SVS_W, Rich_Web_SVS_PT, Rich_Web_SVS_CS, Rich_Web_SVS_BW, Rich_Web_SVS_BS, Rich_Web_SVS_BC, Rich_Web_SVS_BoxShShow, Rich_Web_SVS_BoxShType, Rich_Web_SVS_BoxSh, Rich_Web_SVS_BoxShC, Rich_Web_SVS_Nav_Show, Rich_Web_SVS_Nav_W, Rich_Web_SVS_Nav_H, Rich_Web_SVS_Nav_BW, Rich_Web_SVS_Nav_BS, Rich_Web_SVS_Nav_BC, Rich_Web_SVS_Nav_BR, Rich_Web_SVS_Nav_PB, Rich_Web_SVS_Nav_C, Rich_Web_SVS_Nav_CC, Rich_Web_SVS_Nav_HC, Rich_Web_SVS_Nav_Pos, Rich_Web_SVS_T_Show, Rich_Web_SVS_TBgC, Rich_Web_SVS_TC, Rich_Web_SVS_TFS, Rich_Web_SVS_TFF, Rich_Web_SVS_D_Show, Rich_Web_SVS_DC, Rich_Web_SVS_DFS, Rich_Web_SVS_DFF, Rich_Web_SVS_LC, Rich_Web_SVS_LFS, Rich_Web_SVS_LFF, Rich_Web_SVS_LHC, Rich_Web_SVS_Arr_Show, Rich_Web_SVS_Arr_Type, Rich_Web_SVS_Arr_S, Rich_Web_SVS_Arr_C, Rich_Web_SVS_Arr_BgC, Rich_Web_SVS_Arr_BW, Rich_Web_SVS_Arr_BS, Rich_Web_SVS_Arr_BC, Rich_Web_SVS_Arr_BR, Rich_Web_SVS_PIC, Rich_Web_SVS_PIBgC, Rich_Web_SVS_PIBR, Rich_Web_SVS_PIHC, Rich_Web_SVS_PIHBgC, Rich_Web_SVS_Eff, Rich_Web_SVS_LText) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, 'Simple Video Slider 2', 'Simple Video Slider', '650', '5', '1000', '4', 'solid', '#ffffff', 'on', '', '40', '#000000', 'on', '10', '10', '0', 'solid', 'rgba(0,144,170,0.8)', '20', '2', 'rgba(0,144,170,0.8)', 'rgba(255,255,255,0.8)', 'rgba(255,255,255,0.8)', 'top', 'on', 'rgba(0,144,170,0.9)', '#ffffff', '23', 'Gabriola', 'on', '#ffffff', '20', 'Gabriola', '#0090aa', '18', 'Arial', 'rgba(0,115,170,0.64)', 'on', 'caret', '30', '#000000', 'rgba(255,255,255,0.8)', '0', 'solid', '#ffffff', '1', 'rgba(0,144,170,0.7)', 'rgba(255,255,255,0.7)', '15', '#dd3333', 'rgba(255,255,255,0.7)', 'fade', 'View More'));
	}
	$Rich_Web_VS6=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name10 WHERE id>%d",0));
	if(count($Rich_Web_VS6)==0)
	{
		$wpdb->query($wpdb->prepare("INSERT INTO $table_name4 (id, slider_vid_name, slider_Vid_type) VALUES (%d, %s, %s)", '', 'Video Slider/Vertical Thumbnails 1', 'Video Slider/Vertical Thumbnails'));

		$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Video Slider/Vertical Thumbnails 1'));

		$wpdb->query($wpdb->prepare("INSERT INTO $table_name10 (id, RW_VS_ID, Rich_Web_VSlider_Option_Name, Rich_Web_VSlider_Option_Type, Rich_Web_VTVS_AP, Rich_Web_VTVS_APS, Rich_Web_VTVS_APEff, Rich_Web_VTVS_CS, Rich_Web_VTVS_PT, Rich_Web_VTVS_ArrSt, Rich_Web_VTVS_BgC, Rich_Web_VTVS_H, Rich_Web_VTVS_BW, Rich_Web_VTVS_BS, Rich_Web_VTVS_BC, Rich_Web_VTVS_BoxShShow, Rich_Web_VTVS_BoxShType, Rich_Web_VTVS_BoxSh, Rich_Web_VTVS_BoxShC, Rich_Web_VTVS_TShow, Rich_Web_VTVS_TFS, Rich_Web_VTVS_TFF, Rich_Web_VTVS_TC, Rich_Web_VTVS_TBgC, Rich_Web_VTVS_TPos, Rich_Web_VTVS_Th_BW, Rich_Web_VTVS_Th_BS, Rich_Web_VTVS_Th_BC, Rich_Web_VTVS_Th_BR, Rich_Web_VTVS_Th_HBC, Rich_Web_VTVS_LC, Rich_Web_VTVS_LBgC, Rich_Web_VTVS_LFS, Rich_Web_VTVS_LHC, Rich_Web_VTVS_LHBgC, Rich_Web_VTVS_LPos, Rich_Web_VTVS_LType, Rich_Web_VTVS_PC, Rich_Web_VTVS_PBgC, Rich_Web_VTVS_PFS, Rich_Web_VTVS_PHC, Rich_Web_VTVS_PHBgC, Rich_Web_VTVS_PPos, Rich_Web_VTVS_PType, Rich_Web_VTVS_ArrShow, Rich_Web_VTVS_ArrType, Rich_Web_VTVS_ArrFS, Rich_Web_VTVS_ArrPos, Rich_Web_VTVS_ArrC) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, 'Video Slider/Vertical Thumbnails 1', 'Video Slider/Vertical Thumbnails', 'on', '1', 'fade slideshow', '700', '2', '1', '#000000', '350', '0', 'solid', '#ffffff', 'on', 'on', '50', '#6b6b6b', 'on', '22', 'Aldhabi', '#ffffff', 'rgba(0,0,0,0.6)', 'top', '2', 'solid', '#ffffff', '0', '#545454', '#000000', 'rgba(255,255,255,0.7)', '23', '#ffffff', 'rgba(0,0,0,0.7)', 'bottom-right', 'link', 'rgba(0,0,0,0.7)', 'rgba(255,255,255,0.7)', '23', '#ffffff', 'rgba(0,0,0,0.7)', 'bottom-left', 'play-circle', 'on', 'chevron-circle', '25', 'center', '#ffffff'));

		$wpdb->query($wpdb->prepare("INSERT INTO $table_name4 (id, slider_vid_name, slider_Vid_type) VALUES (%d, %s, %s)", '', 'Video Slider/Vertical Thumbnails 2', 'Video Slider/Vertical Thumbnails'));

		$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Video Slider/Vertical Thumbnails 2'));

		$wpdb->query($wpdb->prepare("INSERT INTO $table_name10 (id, RW_VS_ID, Rich_Web_VSlider_Option_Name, Rich_Web_VSlider_Option_Type, Rich_Web_VTVS_AP, Rich_Web_VTVS_APS, Rich_Web_VTVS_APEff, Rich_Web_VTVS_CS, Rich_Web_VTVS_PT, Rich_Web_VTVS_ArrSt, Rich_Web_VTVS_BgC, Rich_Web_VTVS_H, Rich_Web_VTVS_BW, Rich_Web_VTVS_BS, Rich_Web_VTVS_BC, Rich_Web_VTVS_BoxShShow, Rich_Web_VTVS_BoxShType, Rich_Web_VTVS_BoxSh, Rich_Web_VTVS_BoxShC, Rich_Web_VTVS_TShow, Rich_Web_VTVS_TFS, Rich_Web_VTVS_TFF, Rich_Web_VTVS_TC, Rich_Web_VTVS_TBgC, Rich_Web_VTVS_TPos, Rich_Web_VTVS_Th_BW, Rich_Web_VTVS_Th_BS, Rich_Web_VTVS_Th_BC, Rich_Web_VTVS_Th_BR, Rich_Web_VTVS_Th_HBC, Rich_Web_VTVS_LC, Rich_Web_VTVS_LBgC, Rich_Web_VTVS_LFS, Rich_Web_VTVS_LHC, Rich_Web_VTVS_LHBgC, Rich_Web_VTVS_LPos, Rich_Web_VTVS_LType, Rich_Web_VTVS_PC, Rich_Web_VTVS_PBgC, Rich_Web_VTVS_PFS, Rich_Web_VTVS_PHC, Rich_Web_VTVS_PHBgC, Rich_Web_VTVS_PPos, Rich_Web_VTVS_PType, Rich_Web_VTVS_ArrShow, Rich_Web_VTVS_ArrType, Rich_Web_VTVS_ArrFS, Rich_Web_VTVS_ArrPos, Rich_Web_VTVS_ArrC) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, 'Video Slider/Vertical Thumbnails 2', 'Video Slider/Vertical Thumbnails', 'on', '1', 'swing slideshow', '600', '2', '1', '#ffffff', '350', '5', 'solid', '#ffffff', 'on', '', '10', '#c1c1c1', 'on', '22', 'Aldhabi', '#000000', '#ffffff', 'bottom', '2', 'solid', '#ffffff', '0', '#000000', '#000000', '#ffffff', '15', '#ffffff', '#000000', 'top-left', 'link', 'rgba(0,0,0,0.7)', '#ffffff', '15', '#ffffff', '#000000', 'top-right', 'play', 'on', 'angle', '39', 'center', '#000000'));
	}

	$Rich_Web_VS7=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name11 WHERE id>%d",0));
	if(count($Rich_Web_VS7)==0)
	{
		$wpdb->query($wpdb->prepare("INSERT INTO $table_name4 (id, slider_vid_name, slider_Vid_type) VALUES (%d, %s, %s)", '', 'Horizontal Posts Slider 1', 'Horizontal Posts Slider'));

		$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Horizontal Posts Slider 1'));

		$wpdb->query($wpdb->prepare("INSERT INTO $table_name11 (id, RW_VS_ID, Rich_Web_VSlider_Option_Name, Rich_Web_VSlider_Option_Type, Rich_Web_VS_HPS_Loop, Rich_Web_VS_HPS_Cols, Rich_Web_VS_HPS_Speed, Rich_Web_VS_HPS_AP, Rich_Web_VS_HPS_EH, Rich_Web_VS_HPS_PB, Rich_Web_VS_HPS_Car, Rich_Web_VS_HPS_NP_Show, Rich_Web_VS_HPS_NP_NText, Rich_Web_VS_HPS_NP_PText, Rich_Web_VS_HPS_NP_C, Rich_Web_VS_HPS_NP_BgC, Rich_Web_VS_HPS_NP_FS, Rich_Web_VS_HPS_NP_FF, Rich_Web_VS_HPS_NP_BW, Rich_Web_VS_HPS_NP_BS, Rich_Web_VS_HPS_NP_BC, Rich_Web_VS_HPS_NP_BR, Rich_Web_VS_HPS_NP_HC, Rich_Web_VS_HPS_NP_HBgC, Rich_Web_VS_HPS_Cols_BgC, Rich_Web_VS_HPS_Cols_BoxShC, Rich_Web_VS_HPS_Cols_VSEff, Rich_Web_VS_HPS_Cols_StShC, Rich_Web_VS_HPS_Cols_VHEff, Rich_Web_VS_HPS_Cols_HShC, Rich_Web_VS_HPS_TC, Rich_Web_VS_HPS_TFS, Rich_Web_VS_HPS_TFF, Rich_Web_VS_HPS_DShow, Rich_Web_VS_HPS_DC, Rich_Web_VS_HPS_DFS, Rich_Web_VS_HPS_DFF, Rich_Web_VS_HPS_LText, Rich_Web_VS_HPS_LC, Rich_Web_VS_HPS_LFS, Rich_Web_VS_HPS_LFF, Rich_Web_VS_HPS_LHC, Rich_Web_VS_HPS_PText, Rich_Web_VS_HPS_PBgC, Rich_Web_VS_HPS_PC, Rich_Web_VS_HPS_PFS, Rich_Web_VS_HPS_PFF, Rich_Web_VS_HPS_PHC, Rich_Web_VS_HPS_PHBgC, Rich_Web_VS_HPS_Pop_OvC, Rich_Web_VS_HPS_Pop_BW, Rich_Web_VS_HPS_Pop_BS, Rich_Web_VS_HPS_Pop_BC, Rich_Web_VS_HPS_Pop_BoxShShow, Rich_Web_VS_HPS_Pop_BoxShType, Rich_Web_VS_HPS_Pop_BoxSh, Rich_Web_VS_HPS_Pop_BoxShC, Rich_Web_VS_HPS_Pop_CIType, Rich_Web_VS_HPS_Pop_CIS, Rich_Web_VS_HPS_Pop_CIC) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, 'Horizontal Posts Slider 1', 'Horizontal Posts Slider', 'on', '3', '3', '', 'on', '20', 'on', 'on', 'Next', 'Prev', '#6d6d6d', '#ffffff', '20', 'Gabriola', '1', 'solid', '#6d6d6d', '3', '#000000', '#ffffff', '#ffffff', '#6d6d6d', 'none', '#ffffff', 'drop-shadow', '#9e9e9e', '#000000', '24', 'Vijaya', 'on', '#6d6d6d', '14', 'Aldhabi', 'View More ...', '#000000', '18', 'Vijaya', '#6d6d6d', 'Watch Video ...', '#000000', '#ffffff', '13', 'Arial', '#ffffff', '#383838', 'rgba(0,0,0,0.5)', 'none', 'solid', 'rgba(0,144,170,0.5)', 'on', 'on', '19', 'rgba(0,0,0,0.59)', 'rich_web-times', '35', 'rgba(255,255,255,0.8)'));

		$wpdb->query($wpdb->prepare("INSERT INTO $table_name4 (id, slider_vid_name, slider_Vid_type) VALUES (%d, %s, %s)", '', 'Horizontal Posts Slider 2', 'Horizontal Posts Slider'));

		$Rich_Web_VS_ID=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table_name4 WHERE slider_vid_name=%s", 'Horizontal Posts Slider 2'));

		$wpdb->query($wpdb->prepare("INSERT INTO $table_name11 (id, RW_VS_ID, Rich_Web_VSlider_Option_Name, Rich_Web_VSlider_Option_Type, Rich_Web_VS_HPS_Loop, Rich_Web_VS_HPS_Cols, Rich_Web_VS_HPS_Speed, Rich_Web_VS_HPS_AP, Rich_Web_VS_HPS_EH, Rich_Web_VS_HPS_PB, Rich_Web_VS_HPS_Car, Rich_Web_VS_HPS_NP_Show, Rich_Web_VS_HPS_NP_NText, Rich_Web_VS_HPS_NP_PText, Rich_Web_VS_HPS_NP_C, Rich_Web_VS_HPS_NP_BgC, Rich_Web_VS_HPS_NP_FS, Rich_Web_VS_HPS_NP_FF, Rich_Web_VS_HPS_NP_BW, Rich_Web_VS_HPS_NP_BS, Rich_Web_VS_HPS_NP_BC, Rich_Web_VS_HPS_NP_BR, Rich_Web_VS_HPS_NP_HC, Rich_Web_VS_HPS_NP_HBgC, Rich_Web_VS_HPS_Cols_BgC, Rich_Web_VS_HPS_Cols_BoxShC, Rich_Web_VS_HPS_Cols_VSEff, Rich_Web_VS_HPS_Cols_StShC, Rich_Web_VS_HPS_Cols_VHEff, Rich_Web_VS_HPS_Cols_HShC, Rich_Web_VS_HPS_TC, Rich_Web_VS_HPS_TFS, Rich_Web_VS_HPS_TFF, Rich_Web_VS_HPS_DShow, Rich_Web_VS_HPS_DC, Rich_Web_VS_HPS_DFS, Rich_Web_VS_HPS_DFF, Rich_Web_VS_HPS_LText, Rich_Web_VS_HPS_LC, Rich_Web_VS_HPS_LFS, Rich_Web_VS_HPS_LFF, Rich_Web_VS_HPS_LHC, Rich_Web_VS_HPS_PText, Rich_Web_VS_HPS_PBgC, Rich_Web_VS_HPS_PC, Rich_Web_VS_HPS_PFS, Rich_Web_VS_HPS_PFF, Rich_Web_VS_HPS_PHC, Rich_Web_VS_HPS_PHBgC, Rich_Web_VS_HPS_Pop_OvC, Rich_Web_VS_HPS_Pop_BW, Rich_Web_VS_HPS_Pop_BS, Rich_Web_VS_HPS_Pop_BC, Rich_Web_VS_HPS_Pop_BoxShShow, Rich_Web_VS_HPS_Pop_BoxShType, Rich_Web_VS_HPS_Pop_BoxSh, Rich_Web_VS_HPS_Pop_BoxShC, Rich_Web_VS_HPS_Pop_CIType, Rich_Web_VS_HPS_Pop_CIS, Rich_Web_VS_HPS_Pop_CIC) VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", '', $Rich_Web_VS_ID[0]->id, 'Horizontal Posts Slider 2', 'Horizontal Posts Slider', 'on', '4', '4', 'on', 'on', '10', 'on', 'on', 'Next', 'Prev', '#939393', '#ffffff', '16', 'Gabriola', '2', 'solid', '#939393', '3', '#000000', '#ffffff', '#ffffff', '#939393', 'none', '#ffffff', 'grayscale', '#000000', '#020000', '23', 'Vijaya', 'on', '#666666', '14', 'Aldhabi', 'View More ...', '#000000', '16', 'Vijaya', '#939393', 'Watch Video ...', '#000000', '#ffffff', '13', 'Arial', '#a3a3a3', '#000000', 'rgba(0,0,0,0.9)', '0', 'none', 'rgba(0,144,170,0.5)', 'on', 'on', '19', 'rgba(0,0,0,0.59)', 'rich_web-times', '35', '#0090aa'));
	}
?>